package: anaconda-client

platform:
  - linux-32
  - linux-64
  - osx-64
  - win-32
  - win-64

engine:
 - python=2.7
 - python=3.4
 - python=3.5

install:
  - conda install pip setuptools clyent pillow psutil
  - pip install coverage==3.7.1 mock
  - python setup.py develop

test:
  - conda config --add channels https://conda.anaconda.org/t/an-1126452d-8e3d-439a-9763-03b5696f4f97/binstar
  - conda config --add channels conda-kapsel
  - conda install -y nbformat conda-kapsel
  - python binstar_client/tests/runtests.py

script:
  - conda build conda.recipe

build_targets: [conda]

# ---
# Upload python sdist for python2 only since it does not depend on the python version
# engine: python=2.7
# platform: linux-64
# env: PYPI=1
# build_targets: [pypi]
# script:
#   - conda build .
#   - python setup.py sdist
