# https://travis-ci.org/Anaconda-Platform/anaconda-client

language: python
sudo: false
branches:
  only:
    - 1.6.x
    - 1.7.x
    - develop

env:
  global:
    # Environment variables used by astropy helpers
    - CONDA_CHANNELS="https://conda.anaconda.org/t/$ANACONDA_ORG_TOKEN/binstar conda-kapsel"
    - CONDA_DEPENDENCIES="pip setuptools=23.0.0 clyent pillow psutil nbformat anaconda-project mock pytest pytest-cov"
    - PIP_DEPENDENCIES="codecov coverage==3.7.1 freezegun==0.3.9"

matrix:
  include:
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.6

install:
  # Use Astropy ci helpers for initial setup
  - git clone git://github.com/astropy/ci-helpers.git --depth=1
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
  - python setup.py develop

script:
  - pytest binstar_client --cov=binstar_client

after_success:
  - codecov
