# https://travis-ci.org/Anaconda-Platform/anaconda-client

language: python
sudo: false
branches:
  only:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - master

env:
  global:
    - CONDA_TEST_DEPENDENCIES="anaconda-project flake8 mock pillow pytest pytest-cov"
    - PIP_TEST_DEPENDENCIES="codecov freezegun"
    - SUDO=""

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.5
    - os: linux
      arch: arm64
      language: generic
      env: PYTHON_VERSION=3.7
    - os: linux
      arch: arm64
      language: generic
      env: PYTHON_VERSION=3.6

cache:
  directories:
    - $HOME/condacache/pkgs
    - $HOME/.cache/pip

before_install:
  # Install latest miniconda
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
      SUDO=sudo;
      wget -q "https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh" -O archiconda.sh;
      chmod +x archiconda.sh;
      bash archiconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      $SUDO cp -r $HOME/miniconda/bin/* /usr/bin/;
      source "$HOME"/miniconda/etc/profile.d/conda.sh;
      service activate;
    else
      if [[ "$PYTHON_VERSION" == "2.7" ]]; then
        MINICONDA_PYVERSION=2;
      else
        MINICONDA_PYVERSION=3;
      fi;
    fi;
        if [[ "${TRAVIS_CPU_ARCH}" != "arm64" ]]; then
          echo "Fetching Python $MINICONDA_PYVERSION miniconda";
          wget https://repo.anaconda.com/miniconda/Miniconda$MINICONDA_PYVERSION-latest-MacOSX-x86_64.sh -O miniconda.sh;
          bash miniconda.sh -b -p "$HOME"/miniconda;
          source "$HOME"/miniconda/etc/profile.d/conda.sh;
          $SUDO conda activate base;
        fi;
  # Configure conda and update it
  - $SUDO conda config --set always_yes yes --set auto_update_conda false
  - $SUDO conda config --add pkgs_dirs ~/condacache/pkgs
  - $SUDO conda update -n root conda -q --no-pin

  # Install dependencies. This include test and lint dependencies
  - $SUDO conda create -n test python=$PYTHON_VERSION
  - $SUDO conda install -n test --file requirements.txt -q --no-pin
  - $SUDO conda install -n test $CONDA_TEST_DEPENDENCIES -q --no-pin
  - source activate test
sudo: false
install:
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
      $SUDO chmod 777 /home/travis/miniconda/envs/test/lib/python$PYTHON_VERSION/site-packages/;
      $SUDO rm /usr/bin/lsb_release;
      $SUDO cp -r /home/travis/miniconda/envs/test/lib/python$PYTHON_VERSION /usr/lib/python$PYTHON_VERSION;
    fi;
  - pip install --user $PIP_TEST_DEPENDENCIES

  # Install this package
  - pip install --user -e .

script:
  - $SUDO conda info --json
  # - flake8 binstar_client
  - pytest binstar_client --cov=binstar_client

after_success:
  - codecov
