{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject['project'] %}

{% set name = project['name'] %}
{% set version = VERSION %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps .
  noarch: python
  entry_points:
    - binstar = binstar_client.scripts.cli:main
    - conda-server = binstar_client.scripts.cli:main

requirements:
  host:
    - python {{ project['requires-python'] }}
    - pip
    - setuptools
  run:
    - python
    - anaconda-anon-usage >=0.4.0
    - conda-package-handling >=1.7.3
    - conda-package-streaming >=0.9.0
    - defusedxml >=0.7.1
    - nbformat >=4.4.0
    - python-dateutil >=2.6.1
    - pytz >=2021.3
    - pyyaml >=3.12
    - platformdirs >=3.10.0,<5.0
    - requests >=2.20.0
    - requests-toolbelt >=0.9.1
    - setuptools >=58.0.4
    - tqdm >=4.56.0
    - urllib3 >=1.26.4
    - anaconda-cli-base >=0.4.0

test:
  requires:
    - conda
  commands:
    - anaconda -h
    - anaconda --version
  imports:
    - binstar_client
    - binstar_client.commands
    - binstar_client.inspect_package
    - binstar_client.mixins
    - binstar_client.scripts
    - binstar_client.utils
    - binstar_client.utils.notebook

about:
  home: https://anaconda.org
  license: {{ project['license']['text'] }}
  license_family: BSD
  license_file: LICENSE.md
  summary: {{ project['description'] }}
  description: |
    Anaconda-client is used to connect to and manage your anaconda.org account,
    upload packages you have created, and generate access tokens to manage packages.
  doc_url: https://www.anaconda.com/docs/tools/anaconda-org/main
  doc_source_url: https://github.com/anaconda/anaconda-client/blob/master/README.md
  dev_url: https://github.com/anaconda/anaconda-client
